function A_n = A_n_cartpole(in1,u1)
%A_N_CARTPOLE
%    A_N = A_N_CARTPOLE(IN1,U1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Dec-2020 16:51:24

x2 = in1(2,:);
x4 = in1(4,:);
t2 = cos(x2);
t3 = sin(x2);
t4 = x4.^2;
t5 = t3.^2;
t6 = t2+t4;
t7 = t5+1.0;
t8 = 1.0./t7;
t9 = t8.^2;
A_n = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-t8.*(t5-t2.*t6)-t2.*t3.*t9.*(u1+t3.*t6).*2.0,-t8.*(t2.*2.0-t4.*t5-t3.*u1+t2.^2.*t4)+t2.*t3.*t9.*(t3.*2.0+t2.*u1+t2.*t3.*t4).*2.0,1.0,0.0,0.0,0.0,0.0,1.0,t3.*t8.*x4.*2.0,t2.*t3.*t8.*x4.*-2.0],[4,4]);
