function B_n = B_cartpole(x, u)
%B_CARTPOLE
%    B_N = B_CARTPOLE(X2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    13-Dec-2020 22:01:30

t2 = sin(x(2));
t3 = t2.^2;
t4 = t3+1.0;
t5 = 1.0./t4;
B_n = [0.0;0.0;t5;-t5.*cos(x(2))];
