function B_n = B_n_cartpole(in1,u1)
%B_N_CARTPOLE
%    B_N = B_N_CARTPOLE(IN1,U1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Dec-2020 16:51:25

x2 = in1(2,:);
t2 = sin(x2);
t3 = t2.^2;
t4 = t3+1.0;
t5 = 1.0./t4;
B_n = [0.0;0.0;t5;-t5.*cos(x2)];
