function f = cartpole_dynamics(x, u)
%CARTPOLE_DYNAMICS
%    F = CARTPOLE_DYNAMICS(U1,X2,X3,X4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    13-Dec-2020 22:01:30

t2 = cos(x(2));
t3 = sin(x(2));
t4 = x(4).^2;
t5 = t3.^2;
t6 = t5+1.0;
t7 = 1.0./t6;
f = [x(3);x(4);t7.*(u(1)+t3.*(t2+t4));-t7.*(t3.*2.0+t2.*u(1)+t2.*t3.*t4)];
