function f = f_n_cartpole(in1,u1)
%F_N_CARTPOLE
%    F = F_N_CARTPOLE(IN1,U1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Dec-2020 16:51:25

x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = cos(x2);
t3 = sin(x2);
t4 = x4.^2;
t5 = t3.^2;
t6 = t5+1.0;
t7 = 1.0./t6;
f = [x3;x4;t7.*(u1+t3.*(t2+t4));-t7.*(t3.*2.0+t2.*u1+t2.*t3.*t4)];
